services:
  postgres:
    image: postgres:16
    container_name: aegisid-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aegisid
      POSTGRES_PASSWORD: aegisid_password
      POSTGRES_DB: aegisid_db
    ports:
      - "5432:5432"
    volumes:
      - aegisid_postgres_data:/var/lib/postgresql/data

volumes:
  aegisid_postgres_data:
